---
title: "Homework-4"
author: "Mary Cadogan"
format: pdf
editor: visual
---

1.  Mathematical: H0: β~1~ = 0

    HA: β~1~ ≠ 0

    Biological: H0: Fish length does not predict fish weight for trout perch.

    HA: Fish length does predict fish weight for trout perch.

```{r}
library(tidyverse)
library(here)
library(naniar)
library(flextable)
library(performance)
library(broom)
library(car)
library(ggeffects)
```

```{r}
fish_data <- read_csv(here("code", "ntl6_v12.csv"))
```

2.  

```{r}
troutperch_summary <- fish_data %>% 
  filter(spname == "TROUTPERCH") %>% 
  group_by("length", "weight") 
```

```{r}
gg_miss_var(troutperch_summary) %>% 
  labs(plot.title = "The missing data from the weight column will impact the hypotheses due to weight being the dependent variable we are testing against the independent variable of fish lengths.")
  
```

```{r}
ggplot(data = troutperch_summary, aes(x = length, y = weight)) + 
  geom_point()
```

4\.

```{r}
troutperch_object <- lm(weight ~ length, data = troutperch_summary)

par(mfrow =c(2,2))
plot(troutperch_object)
```

5.  After looking at

6\.

```{r}
trout_summarytable <- summary(troutperch_object)

trout_summarytable
```

```{r}
trout_anova <-anova(troutperch_object)

trout_anova_table <- tidy(trout_anova) %>% 
  mutate(across(sumsq:meansq, ~ round(.x, digits = 4))) %>%
  mutate(statistic = round(statistic, digits = 1)) %>% 
  mutate(p.value = case_when(p.value < 0.001 ~ "< 0.001")) %>%
  flextable() %>% 
  set_header_labels(df = "Degrees of Freedom", 
                    sumsq = "Sum of squares",
                    meansq = "Mean squares",
                    statistic = "F-statistic",
                    p.value = "p-value")

trout_anova_table
```

```{r}
trout_anova_table <- tidy(trout_anova) %>% 
  mutate(across(sumsq:meansq, ~ round(.x, digits = 4))) %>%
  mutate(statistic = round(statistic, digits = 1)) %>% 
  mutate(p.value = case_when(p.value < 0.001 ~ "< 0.001")) %>%
  flextable() %>% 
  set_header_labels(df = "Degrees of Freedom", 
                    sumsq = "Sum of squares",
                    meansq = "Mean squares",
                    statistic = "F-statistic",
                    p.value = "p-value")

trout_anova_table
```

8.  The ANOVA table relates to the information from the summary() object
9.  

```{r}
plot_predictions
```
